# Generated by Django 5.2.5 on 2026-05-18 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_book_g_tag_alter_book_s_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='대출 신청일')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to='books.book', verbose_name='신청 도서')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to=settings.AUTH_USER_MODEL, verbose_name='신청자')),
            ],
            options={
                'verbose_name': '대출 신청',
                'verbose_name_plural': '대출 신청',
                'ordering': ['-requested_at'],
            },
        ),
    ]
